---
# tasks file for httpd
- name: Module Yum
  yum:
    name: httpd
    state: latest
  notify: 
    - "restart httpd"
- name: create index.html file
  file: 
    name: /var/www/html/index.html
    state: touch
- name: Changement de port
  template:
    src: httpd.j2
    dest: /etc/httpd/conf/httpd.conf
  notify:
    - "restart httpd"
- name: Copie de fichier
  copy:
    src: git.yml 
    dest: /vagrant_data/
- name: add web content
  lineinfile:
    line: "{{ item }}"
    path: /var/www/html/index.html
  with_items:
    - "ceci est un test, veuillez ne pas en tenir compte"
    - "Je vous remercie"
